PycharmProjects/cryptowallet/crypto/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'crypto'

urlpatterns = [
    url(r'^$', views.home, name='home'),

    # All Accounts - /accounts/
    url(r'^accounts/$', views.accounts, name='accounts'),

    # Accounts Details - /accounts/<account>/
    url(r'^accounts/(?P<account>0x[a-fA-F0-9]+)/$', views.account_details, name='account_details'),

    # Accounts Details - /new_account/
    url(r'^new_account/$', views.new_account, name='new_account'),

    #create_new_account
    # url(r'^new_account/(?P<password>[a-fA-F0-9]+)/$', views.create_new_account, name='create_new_account'),

    # Tranasaction
    url(r'^new_account/send_transaction$', views.send_transaction, name='send_transaction'),
]

PycharmProjects/cryptowallet/cryptowallet/urls.py
from django.conf.urls import url,include
from django.contrib import admin

app_name = 'crypto'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'crypto/', include('crypto.urls'))
]

PycharmProjects/cryptowallet/crypto/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Account(models.Model):
    username = models.CharField(max_length=250)
    password = models.CharField(max_length=1000000)
    address = models.CharField(max_length=500)

    # Override String Representation
    def __str__(self):
        return self.name


class Transaction(models.Model):
    from_address = models.CharField(max_length=250)
    to_address = models.CharField(max_length=250)
    amount = models.CharField(max_length=250)

    def __str__(self):
        return self.from_address

PycharmProjects/cryptowallet/crypto/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Transaction


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password']


class TransactionForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Transaction
        fields = ['from_address','to_address','amount','password']

PycharmProjects/cryptowallet/crypto/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import requests
import json
from django.shortcuts import render
from .models import Account
import time
from .forms import UserForm,TransactionForm

WAIT_TIME = 15
KEYS_DIR = r"/home/auxesis/Documents/Ethereum/PrivateEthr1"
PORT = 8546 # 6060
URL = 'http://localhost:' + str(PORT)
headers = {'Content-type': 'application/json'}
payload = {"jsonrpc": "2.0","id": 1}

# Create your views here.
def home(request):
    return render(request, 'crypto/home.html', {'number' : 1})


def accounts(request):
    template = 'crypto/all_accounts.html'
    payload['method'] = 'eth_accounts'
    payload['params'] = []


    # response = session.post('http://localhost:8501', json=payload, headers=headers)
    # print('raw json response: {}'.format(response.json()))
    # print('network id: {}'.format(response.json()['result']))

    if request.method == 'GET' :
        try:
            response = requests.post(URL, data=json.dumps(payload), headers=headers)
            json_data = json.loads(response.text)

            result = json_data['result']
            final_result = []
            for address in result:
                data_dict = {}
                balance = get_balance(request, address)
                data_dict['address'] = address
                data_dict['balance'] = str(int(balance, 16))
                final_result.append(data_dict)

            return render(request, template, {'accounts': final_result})
        except Exception as e:
            return render(request, template,{'error_message' : str(e)})

    return render(request, template, {'accounts': ['Bad Request']})



def get_balance(request, address):
    payload['method'] = 'eth_getBalance'
    payload['params'] = [address,'latest']
    try:
        response = requests.post(URL, data=json.dumps(payload), headers=headers)
        json_data = json.loads(response.text)
        return json_data['result']
    except Exception as e:
        return str(e)


def account_details(request):
    pass


def new_account(request):
    template = 'crypto/new_account.html'
    if request.method == 'GET':
        return render(request, template, {'error_message' : ''})


def new_account(request):
    template = 'crypto/new_account.html'
    if request.method == 'GET':
        form = UserForm(None)
        return render(request, template, {'error_message' : '','form' : form})

    if request.method == 'POST':
        try :
            form = UserForm(request.POST)

            if form.is_valid():
                cleaned_data = form.cleaned_data
                username = cleaned_data['username']
                password = cleaned_data['password']

                payload['method'] = "personal_newAccount"
                payload['params'] = [password]
                response = requests.post(URL, data=json.dumps(payload), headers=headers)
                json_data = json.loads(response.text)

               #user.save()
                form = UserForm(None)
                return render(request, template, {'error_message': 'Success - Addreess : ' + json_data['result'],'form' : form})

        except Exception as e:
            form = UserForm(None)
            return render(request, template, {'error_message': str(e),'form' : form})


def send_transaction(request):
    template = 'crypto/send_transaction.html'
    if request.method == 'GET':
        form = TransactionForm(None)
        return render(request, template, {'error_message': '', 'form': form})

    if request.method == 'POST':
        try:
            form = TransactionForm(request.POST)

            if form.is_valid():
                cleaned_data = form.cleaned_data
                from_address = cleaned_data['from_address']
                to_address = cleaned_data['to_address']
                amount = cleaned_data['amount']
                password =  cleaned_data['password']

                payload['method'] = 'personal_unlockAccount'
                payload['params'] = [from_address,password]
                response = requests.post(URL, data=json.dumps(payload), headers=headers)
                json_data = json.loads(response.text)

                if 'result' in json_data:
                    if json_data['result'] == True:
                        payload['method'] = "eth_sendTransaction"
                        payload['params'] = [{"from": from_address, "to": to_address, "value": hex(int(amount))}]
                        response = requests.post(URL, data=json.dumps(payload), headers=headers)
                        json_data = json.loads(response.text)

                    form = TransactionForm(None)
                    start_mining()
                    time.sleep(WAIT_TIME)
                    stop_mining()
                    return render(request, template, {'error_message': 'Success : Transaction ID ' + json_data['result'], 'form': form})

                else:
                    form = TransactionForm(None)
                    return render(request, template,{'error_message': 'Error : ' + json_data['error']['message'], 'form': form})

        except Exception as e:
            form = TransactionForm(None)
            return render(request, template, {'error_message': str(e)})



def start_mining():
    payload['method'] = "miner_start"
    payload['params'] = []
    requests.post(URL, data=json.dumps(payload), headers=headers)

def stop_mining():
    payload['method'] = "miner_stop"
    payload['params'] = []
    requests.post(URL, data=json.dumps(payload), headers=headers)

PycharmProjects/cryptowallet/crypto/templates/crypto/account_details.html
{% extends 'crypto/base.html' %}

{% block mybody %}

{% endblock %}

PycharmProjects/cryptowallet/crypto/templates/crypto/all_accounts.html
{% extends 'crypto/base.html' %}

{% block mybody %}
    {% if error_message %}
        <strong> : {{ error_message }}</strong>
    {% else %}

        <table class="table table-dark">
            <thead>
              <tr>
                <th>Address</th>
                <th>Balance</th>
              </tr>
            </thead>
            <tbody>
            {% for account in accounts %}
                    <tr>
                        <td><a href="{% url 'crypto:send_transaction'%}" >{{ account.address }}</a></td>
                        <td>{{ account.balance }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endif %}

{% endblock %}

PycharmProjects/cryptowallet/crypto/templates/crypto/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block mytitle %}Ethereum{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'crypto/style.css' %}"/>﻿
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">

            <!-- Just like option button, in case the user decrease the browser size-->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- Home -->
            <a class="navbar-brand" href="#">Ethereum</a>
        </div>

        <!-- Items id = data-target="#topNavBar" from button-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'crypto:new_account' %}">
                        <span class="fab fa-ethereum" aria-hidden="true"></span>&nbsp New Account
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'crypto:accounts' %}">
                        <span class="fab fa-ethereum" aria-hidden="true"></span>&nbsp Accounts
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'crypto:send_transaction' %}">
                        <span class="fab fa-ethereum" aria-hidden="true"></span>&nbsp Transaction
                    </a>
                </li>
            </ul>

            <!-- Search Box -->
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="query" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>


        </div>

    </div>
</nav>

    {% block mybody %}
    {% endblock %}

</body>
</html>

PycharmProjects/cryptowallet/crypto/templates/crypto/form-template.html
{% for field in form %}
    <div class="form-group">
        <!-- Errors -->
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

PycharmProjects/cryptowallet/crypto/templates/crypto/home.html
{% extends 'crypto/base.html' %}

PycharmProjects/cryptowallet/crypto/templates/crypto/new_account.html
{% extends 'crypto/base.html' %}

{% block mybody %}

    {% if error_message %}
        {{ error_message }}
    {% endif %}

    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Create a new account</h1>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'crypto/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btnsuccess">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

PycharmProjects/cryptowallet/crypto/templates/crypto/send_transaction.html
{% extends 'crypto/base.html' %}

{% block mybody %}

    {% if error_message %}
        {{ error_message }}
    {% endif %}



    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'crypto/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btnsuccess">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}